version: "3"
services:
  proxy:
    build: "."
    network_mode: bridge
    volumes:
      - .:/app
    command: ["python", "proxy.py"]
    environment:
      HTTP_PROXY_PORT: 8080
    ports:
      - "8080:8080"


